---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
            dest: "./{{ item }}-{{ clickhouse_version }}.rpm"
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          ansible.builtin.get_url:
            url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
            dest: "./clickhouse-common-static-{{ clickhouse_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - clickhouse-common-static-{{ clickhouse_version }}.rpm
          - clickhouse-client-{{ clickhouse_version }}.rpm
          - clickhouse-server-{{ clickhouse_version }}.rpm
      notify: Start clickhouse service
      tags: clickhouse
- name: Install Vector
  hosts: vector
  tasks:
    - name: Create directory Vect
      become_user: root
      become: true
      become_method: su
      become_exe: sudo su
      ansible.builtin.file: path=/vect state=directory
    - name: Download Vector
      become_user: root
      become: true
      become_method: su
      become_exe: sudo su
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.21.0/vector-0.21.0-1.x86_64.rpm"
        dest: "/vect"
        mode: 0664
    - name: Install Vector
      become: true
      ansible.builtin.yum:
        name: "/vect/vector-0.21.0-1.x86_64.rpm"
- name: Install nginx
  hosts: lighthouse
  handlers:
    - name: start-nginx
      become: true
      command: nginx
    - name: reload-nginx
      become: true
      command: nginx -s reload
  tasks:
    - name: Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: nginx
      ansible.builtin.yum:
        name: nginx
        state: present
      become: true
    - name: nginx config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      become: true
      notify: reload-nginx
- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: reload-ng
      become: true
      command: nginx -s reload
  tasks:
    - name: clone git
      ansible.builtin.yum:
        name: git
        state: present
      become: true
    - name: Copy git
      git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location_dir  }}"
        clone: yes
        update: yes
    - name: Config lighthouse
      template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      become: true
      notify: reload-ng
