---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy      

