---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
